<doc>
# sectionReport
> 

@author Nicolas Husson <hello@nusson.ninja>
</doc>

<script>
export default {
  name: "sectionReport",
  components: {},
  props: {},
  data() {
    return {
      report: {
        categorie: {},
        espece : ''
      }
    };
  },
  mounted() {},
  methods: {}
};
</script>

<template>
  <div class="sectionReport">
    <h1>Report</h1>
    <div class="formContainer">
      <div class="categorie">
        <label>Catégorie de l'incident</label>
        <select v-model="report.categorie">
          <option v-bind:value="categorie = 'inondations'">Inondations</option>
          <option v-bind:value="categorie = 'crues'">crues</option>
          <option v-bind:value="categorie = 'pluies'">pluies</option>
          <option v-bind:value="categorie = 'insectes'">insectes</option>
        </select>
        <div v-if="report.categorie ==='insectes'">
          <label>Espèces :</label>
          <select v-model="report.especes">
            <option v-bind:value="especes = 'punaises'">Punaises</option>
            <option v-bind:value="especes = 'frelons'">Frelons</option>
          </select>
        </div>
      </div>
      <div class="date">
        <label>Date de l'incident</label>
      </div>
    </div>
  </div>
</template>

<style lang="stylus" scoped>
     
               
  

                                           
      

        
                
                        
                 
            
          
            
               
                     
       
      
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                           
                                                                         
                                                                               
                                                                   
                                                                     
                                                                         
                 
                                                                
            
                             
                                              
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
            
               
                     
       
      
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                           
                                                                     
                                                                 
                                                     
                                                       
                                                           
                 
                                                                
            
                             
                                              
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
            
               
                     
       
      
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                           
                                                           
                                                                 
                                                     
                                                       
                                                           
                 
                                                                
            
                             
                                              
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
            
               
                     
       
      
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                    
                                                           
                                                                 
                                                     
                                                       
                                                           
                 
                                                         
            
                             
                                              
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
            
                
                      
       
      
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                    
                                                           
                                                                 
                                                     
                                                       
                                                           
                 
                                                          
            
                             
                                              
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                    
                                                           
                                                                 
                                                     
                                                       
                 
            
                             
                                              
        
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                    
                                                           
                                                                 
                                                     
                                                       
                 
            
                             
                                              
                                    
                                                           
                                                                 
                                                     
                                                       
                 
            

          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                    
                                                           
                                                                 
                                                     
                                                       
                 
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                    
                                                             
                                                             
                                                             
                                                             
                 
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
                               
                             
                                    
                                                             
                 
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
                               
                             
                                   
                                                             
                 
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
                               
                             
                                   
                                
                                                     
         
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
                               
            
             
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
               
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
        
           

                            

  /**
  * TABLE OF CONTENT
  * --------
  *  - LAYOUT
  *  - DEBUG
  *  - NO_SCOPE
  */

  //  ===LAYOUT===

  //  ===DEBUG===
</style>


<style lang="stylus">
     
               
  

                                           
      

        
                
                        
                 
            
          
            
               
                     
       
      
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                           
                                                                         
                                                                               
                                                                   
                                                                     
                                                                         
                 
                                                                
            
                             
                                              
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
            
               
                     
       
      
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                           
                                                                     
                                                                 
                                                     
                                                       
                                                           
                 
                                                                
            
                             
                                              
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
            
               
                     
       
      
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                           
                                                           
                                                                 
                                                     
                                                       
                                                           
                 
                                                                
            
                             
                                              
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
            
               
                     
       
      
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                    
                                                           
                                                                 
                                                     
                                                       
                                                           
                 
                                                         
            
                             
                                              
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
            
                
                      
       
      
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                    
                                                           
                                                                 
                                                     
                                                       
                                                           
                 
                                                          
            
                             
                                              
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                    
                                                           
                                                                 
                                                     
                                                       
                 
            
                             
                                              
        
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                    
                                                           
                                                                 
                                                     
                                                       
                 
            
                             
                                              
                                    
                                                           
                                                                 
                                                     
                                                       
                 
            

          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                    
                                                           
                                                                 
                                                     
                                                       
                 
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
                               
                             
                                              
                                    
                                                             
                                                             
                                                             
                                                             
                 
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
                               
                             
                                    
                                                             
                 
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
                               
                             
                                   
                                                             
                 
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
                               
                             
                                   
                                
                                                     
         
            
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
                               
            
             
          
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
               
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
        
           

                            
     
               
  

                                           
      

        
                
                        
                 
            
          
              
    
               
             
  
         

          
                             
                   
        
           

                            

  /**
  * TABLE OF CONTENT
  * --------
  *  - LAYOUT
  *  - DEBUG
  *  - NO_SCOPE
  */

  //  ===LAYOUT===

  //  ===DEBUG===
</style>
